trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
       curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

- task: CmdLine@2
  inputs:
    script: 'curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp'

#- script: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
#  displayName: 'Install eksctl'

#- script: sudo mv /tmp/eksctl /usr/local/bin
#  displayName: 'mv eksctl to local bin'

#- script: eksctl version
#  displayName: 'check eksctl version'

# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'aws'
#     command: 'init'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
#    backendServiceAWS: 'aws-for-terraform'
#    backendAWSBucketName: 'terraform-backend-state-manny'
#    backendAWSKey: 'kubernetes-dev.tfstate'

#- task: TerraformTaskV4@4
#  inputs:
#    provider: 'aws'
#    command: 'apply'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
#    environmentServiceNameAWS: 'aws-for-terraform'
# apply
